# Generated by Django 5.2.11 on 2026-03-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_slider_sliderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order']},
        ),
    ]
